name: Build stable-diffusion.cpp

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  get_short_commit_hash:
    runs-on: ubuntu-latest
    outputs:
      hash: ${{ steps.short_commit_hash.outputs.short }}
    steps:
      - name: Prepare commit hash
        id: commit_hash
        run: |
          git clone https://github.com/leejet/stable-diffusion.cpp cache --depth 1
          cd cache
          echo "hash=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
          cd ..
          rm -rf cache
      - name: Get short commit hash
        id: short_commit_hash
        uses: prompt/actions-commit-hash@v3
        with:
          commit: ${{ steps.commit_hash.outputs.hash }}
  build_openblas_avx2_linux:
    needs: get_short_commit_hash
    runs-on: ubuntu-latest
    steps:
      - name: Install Deps
        run: |
          sudo apt-get update
          sudo apt-get install ccache ninja-build libopenblas-dev zip -y
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: leejet/stable-diffusion.cpp
          submodules: recursive
      - name: Build
        run: |
          mkdir build
          cd build
          cmake .. -G "Ninja" -DCMAKE_BUILD_TYPE=Release -DGGML_OPENBLAS=ON -DGGML_AVX2=ON -DSD_BUILD_SHARED_LIBS=ON
          cmake --build . --config Release -j $(nproc)
      - name: Pack
        run: |
          mkdir -p build/dist
          find . -name "*.so" -exec mv {} build/bin/ \;
          cd build/bin/ || exit
          zip ../dist/sd-master-${{ needs.get_short_commit_hash.outputs.hash }}-bin-linux-openblas-avx2-x64.zip ./*
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: openblas-avx2-linux
          path: build/dist/sd-master-${{ needs.get_short_commit_hash.outputs.hash }}-bin-linux-openblas-avx2-x64.zip
  build_sycl_avx512_linux:
    needs: get_short_commit_hash
    runs-on: ubuntu-latest
    steps:
      - name: Install Deps
        run: |
          wget -O- https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB | gpg --dearmor | sudo tee /usr/share/keyrings/oneapi-archive-keyring.gpg > /dev/null
          echo "deb [signed-by=/usr/share/keyrings/oneapi-archive-keyring.gpg] https://apt.repos.intel.com/oneapi all main" | sudo tee /etc/apt/sources.list.d/oneAPI.list
          sudo apt-get update
          sudo apt-get install ccache intel-basekit intel-oneapi-mkl intel-oneapi-mkl-devel ninja-build zip -y
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: leejet/stable-diffusion.cpp
          submodules: recursive
      - name: Build
        run: |
          mkdir build
          cd build
          source /opt/intel/oneapi/setvars.sh
          cmake .. -G "Ninja" -DCMAKE_BUILD_TYPE=Release -DSD_SYCL=ON -DCMAKE_C_COMPILER=icx -DCMAKE_CXX_COMPILER=icpx -DGGML_AVX512=ON -DSD_BUILD_SHARED_LIBS=ON
          cmake --build . --config Release -j $(nproc)
      - name: Pack
        run: |
          mkdir -p build/dist
          find . -name "*.so" -exec mv {} build/bin/ \;
          cd build/bin/ || exit
          zip ../dist/sd-master-${{ needs.get_short_commit_hash.outputs.hash }}-bin-linux-sycl-avx512-x64.zip ./*
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sycl-avx512-linux
          path: build/dist/sd-master-${{ needs.get_short_commit_hash.outputs.hash }}-bin-linux-sycl-avx512-x64.zip
  build_sycl_avx2_linux:
    needs: get_short_commit_hash
    runs-on: ubuntu-latest
    steps:
      - name: Install Deps
        run: |
          wget -O- https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB | gpg --dearmor | sudo tee /usr/share/keyrings/oneapi-archive-keyring.gpg > /dev/null
          echo "deb [signed-by=/usr/share/keyrings/oneapi-archive-keyring.gpg] https://apt.repos.intel.com/oneapi all main" | sudo tee /etc/apt/sources.list.d/oneAPI.list
          sudo apt-get update
          sudo apt-get install ccache intel-basekit intel-oneapi-mkl intel-oneapi-mkl-devel ninja-build zip -y
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: leejet/stable-diffusion.cpp
          submodules: recursive
      - name: Build
        run: |
          mkdir build
          cd build
          source /opt/intel/oneapi/setvars.sh
          cmake .. -G "Ninja" -DCMAKE_BUILD_TYPE=Release -DSD_SYCL=ON -DCMAKE_C_COMPILER=icx -DCMAKE_CXX_COMPILER=icpx -DGGML_AVX2=ON -DSD_BUILD_SHARED_LIBS=ON
          cmake --build . --config Release -j $(nproc)
      - name: Pack
        run: |
          mkdir -p build/dist
          find . -name "*.so" -exec mv {} build/bin/ \;
          cd build/bin/ || exit
          zip ../dist/sd-master-${{ needs.get_short_commit_hash.outputs.hash }}-bin-linux-sycl-avx2-x64.zip ./*
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sycl-avx2-linux
          path: build/dist/sd-master-${{ needs.get_short_commit_hash.outputs.hash }}-bin-linux-sycl-avx2-x64.zip
  build_cu124_avx2_linux:
    needs: get_short_commit_hash
    runs-on: ubuntu-latest
    steps:
      - name: Install CUDA 12.4.1
        id: install-cuda
        uses: MZWNET/cuda-toolkit@mod
        with:
          cuda: "12.4.1"
          method: network
      - name: Install Deps
        run: sudo apt-get install ccache zip ninja-build -y
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: leejet/stable-diffusion.cpp
          submodules: recursive
      - name: Build
        run: |
          mkdir build
          cd build
          cmake .. -G "Ninja" -DCMAKE_BUILD_TYPE=Release -DSD_CUBLAS=ON -DSD_FAST_SOFTMAX=ON -DGGML_AVX512=ON -DSD_BUILD_SHARED_LIBS=ON
          cmake --build . --config Release -j $(nproc)
      - name: Pack
        run: |
          mkdir -p build/dist
          find . -name "*.so" -exec mv {} build/bin/ \;
          cd build/bin/ || exit
          zip ../dist/sd-master-${{ needs.get_short_commit_hash.outputs.hash }}-bin-linux-avx2-cublas-cu124-x64.zip ./*
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cu124-avx2-linux
          path: build/dist/sd-master-${{ needs.get_short_commit_hash.outputs.hash }}-bin-linux-avx2-cublas-cu124-x64.zip
  build_cu126_avx512_linux:
    needs: get_short_commit_hash
    runs-on: ubuntu-latest
    steps:
      - name: Install CUDA 12.6.2
        id: install-cuda
        uses: MZWNET/cuda-toolkit@mod
        with:
          cuda: "12.6.2"
          method: network
      - name: Install Deps
        run: sudo apt-get install ccache zip ninja-build -y
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: leejet/stable-diffusion.cpp
          submodules: recursive
      - name: Build
        run: |
          mkdir build
          cd build
          cmake .. -G "Ninja" -DCMAKE_BUILD_TYPE=Release -DSD_CUBLAS=ON -DCMAKE_CUDA_ARCHITECTURES=86 -DSD_FAST_SOFTMAX=ON -DGGML_AVX512=ON -DSD_BUILD_SHARED_LIBS=ON
          cmake --build . --config Release -j $(nproc)
      - name: Pack
        run: |
          mkdir -p build/dist
          find . -name "*.so" -exec mv {} build/bin/ \;
          cd build/bin/ || exit
          zip ../dist/sd-master-${{ needs.get_short_commit_hash.outputs.hash }}-bin-linux-avx512-cublas-cu126-x64.zip ./*
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cu126-avx512-linux
          path: build/dist/sd-master-${{ needs.get_short_commit_hash.outputs.hash }}-bin-linux-avx512-cublas-cu126-x64.zip
  build_cu124_avx512_win:
    needs: get_short_commit_hash
    runs-on: windows-latest
    steps:
      - name: Setup VS Dev Environment
        uses: seanmiddleditch/gha-setup-vsdevenv@v4
      - name: Install CUDA 12.4
        id: install-cuda
        uses: MZWNET/cuda-toolkit@mod
        with:
          cuda: "12.4.1"
          method: network
          sub-packages: '["nvcc", "cudart", "cublas", "cublas_dev", "thrust", "visual_studio_integration"]'
      - name: Setup ccache
        uses: Chocobo1/setup-ccache-action@v1
        with:
          windows_compile_environment: msvc
      - name: Install Ninja
        uses: urkle/action-get-ninja@v1
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: leejet/stable-diffusion.cpp
          submodules: recursive
      - name: Build
        run: |
          mkdir build
          cd build
          cmake .. -G "Ninja" -DCMAKE_BUILD_TYPE=Release -DSD_CUBLAS=ON -DCMAKE_CUDA_ARCHITECTURES=86 -DSD_FAST_SOFTMAX=ON -DGGML_AVX512=ON -DSD_BUILD_SHARED_LIBS=ON
          cmake --build . --config Release -j $env:NUMBER_OF_PROCESSORS
      - name: Pack
        run: |
          cd build\bin\
          7z a ..\dist\sd-master-${{ needs.get_short_commit_hash.outputs.hash }}-bin-win-avx512-cublas-cu124-x64.zip .
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cu124-avx512-win
          path: build/dist/sd-master-${{ needs.get_short_commit_hash.outputs.hash }}-bin-win-avx512-cublas-cu124-x64.zip
  release:
    runs-on: ubuntu-latest
    needs: [get_short_commit_hash, build_openblas_avx2_linux, build_sycl_avx512_linux, build_sycl_avx2_linux, build_cu126_avx512_linux, build_cu124_avx2_linux, build_cu124_avx512_win]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: |
            dist/
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: sd-master-${{ needs.get_short_commit_hash.outputs.hash }}
          name: Binary build for stable-diffusion.cpp (${{ needs.get_short_commit_hash.outputs.hash }})
          body: |
            This release contains the x86_64 binary of [stable-diffusion.cpp](https://github.com/leejet/stable-diffusion.cpp).
          files: dist/**/*
          fail_on_unmatched_files: true
